# Generated by Django 5.1.3 on 2024-11-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zipcode',
        ),
    ]
