# Generated by Django 5.1.3 on 2024-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_price_order_quantity_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('similarity', models.FloatField()),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
